export const frontImagePaths = [
	'images/bild1.webp',
	'images/bild2.webp',
	'images/bild3.webp',
	'images/bild4.webp',
	'images/bild5.webp',
	'images/bild6.webp',
	'images/bild7.jpg',
	'images/bild8.jpg',
	'images/bild9.jpg',
	'images/bild10.jpg',
	'images/bild11.jpg',
	'images/bild12.jpg',
	'images/bild13.jpg',
	'images/bild14.jpg',
	'images/bild15.jpg',
	'images/bild16.jpg',
	'images/bild17.jpg',
	'images/bild18.jpg',
	'images/bild19.jpg',
	'images/bild20.jpg',
	'images/bild21.jpg',
	'images/bild22.jpg',
	'images/bild23.jpg',
	'images/bild24.jpg',
	'images/bild25.jpg',
	'images/bild26.jpg',
	'images/bild27.jpg',
	'images/bild28.jpg',
	'images/bild29.jpg',
	'images/bild30.jpg',
	'images/bild31.jpg',
	'images/bild32.jpg',
];

export const backImagePaths = ['images/card.webp']; // Common backside image
